server:
  port: 8080
  error:
    include-message: always

spring:
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hih
    password: hih
    username: postgres
  jpa:
    hibernate:
        ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
